# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60fcf890f329ca819411b4e5aed820b6a2abcc23997aea2f28250d23d08fd57ac8809ca2eadd91f5e9f32237616c385aac6b84853318cd1b22a17dbd91a86321

test:
  secret_key_base: 9a9cbcc7b745fb285a1f8ecd84ee0682437bb212dd2f857f85dde4d4a60496a6fce5cc2425b2193e99ca45dbbe8ddce36a8c883d78bab3dddcc3fcab225148c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
